### ISSUE TITLE
Icons looking differnt in search option

### ISSUE THREAD

**Issue by Ramton03** [privau/searxng#25]
![2023-09-19_16-22](https://github.com/privau/searxng/assets/49825977/1136c352-26f3-4324-b5cd-c12f5cd814bc)
Is this intentional?

**Comment by vojkovic** [comment]
Definitely not! I'll rebuild the css and see if that will fix it. Just a minute please.

**Comment by vojkovic** [comment]
Edited some .less files, [some changes were made upstream](https://github.com/searxng/searxng/commit/a55e0ac553e608e5657573a8173aa5a040a49054). Has been mostly fixed in https://github.com/privau/searxng/commit/afa6482a856e2643b4fb94bf5b21021de53a977c, although I do plan to go back and change some styling over the coming days.

Please wait for the changes to propagate to production. Thanks for your issue, do let me know if there are any styling problems after about 2 hours.
